"""Walk a target (one repository, or a folder of repositories) and decide which
files are worth reading, what language each is, and what role it plays.

    python3 inventory.py --target /path/to/repo-or-folder

Everything here is deterministic. Nothing is sent anywhere. The role is a
path-and-content heuristic that later feeds Jev as `file.role`, so a wrong
role costs accuracy on that file, not correctness of the run.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path

LANGUAGES = {
    ".py": "python", ".ts": "typescript", ".tsx": "typescript", ".js": "javascript",
    ".jsx": "javascript", ".mjs": "javascript", ".cjs": "javascript", ".go": "go",
    ".java": "java", ".kt": "kotlin", ".rb": "ruby", ".php": "php", ".cs": "csharp",
    ".rs": "rust", ".tf": "terraform", ".yaml": "yaml", ".yml": "yaml", ".json": "json",
    ".toml": "toml", ".sh": "shell", ".bash": "shell", ".zsh": "shell", ".sql": "sql",
    ".html": "html", ".env": "dotenv",
}
CONFIG_BASENAMES = {"Dockerfile", "Containerfile", "Procfile", "Makefile", "Jenkinsfile", ".env", ".env.example", ".env.local"}
CI_PATHS = re.compile(r"(^|/)(\.github/workflows/|\.gitlab-ci\.yml|\.circleci/|cloudbuild[^/]*\.ya?ml|Jenkinsfile|azure-pipelines|bitbucket-pipelines|\.husky/|buildspec\.ya?ml)")
INFRA_PATHS = re.compile(r"(^|/)(infra|infrastructure|terraform|deploy|k8s|kubernetes|helm|charts?)(/|$)")
TEST_PATHS = re.compile(r"(^|/)(tests?|__tests__|spec|specs|e2e|fixtures?|__mocks__|testdata|mock-data|mocks)(/|$)|(\.|_)(test|spec)\.[a-z]+$|^test_[^/]+\.py$|(^|/)test_[^/]+\.py$|conftest\.py$")
SKIP_DIRS = {"node_modules", ".git", ".hg", ".svn", "__pycache__", ".tox", ".mypy_cache",
             ".pytest_cache", ".ruff_cache", "dist", "build", ".next", ".nuxt", "coverage", "vendor", "third_party",
             ".terraform", ".idea", ".vscode", "target", "out", ".cache", ".parcel-cache", "site-packages", ".opencode"}
SKIP_FILE_RE = re.compile(r"(\.min\.(js|css)$|\.lock$|-lock\.(json|yaml)$|\.d\.ts$|\.map$|\.snap$|\.svg$|\.png$|\.jpe?g$|\.gif$|\.ico$|\.woff2?$|\.ttf$|\.pdf$|\.zip$|\.pyc$|uv\.lock$|Cargo\.lock$|go\.sum$)")
GENERATED_RE = re.compile(r"(@generated|Code generated by|DO NOT EDIT|autogenerated|auto-generated)", re.I)
DOC_EXT = {".md", ".rst", ".txt", ".adoc"}
MAX_FILE_BYTES = 600_000

HANDLER_HINTS = re.compile(
    r"@app\.(route|get|post|put|delete|patch)|@router\.|@bp\.route|functions_framework|"
    r"def (main|handler|handle|lambda_handler)\(|express\(\)|router\.(get|post|put|delete|patch|use)\(|"
    r"app\.(get|post|put|delete|patch)\(|fastify\.|@(Get|Post|Put|Delete|Patch|Controller)\(|"
    r"http\.HandleFunc|gin\.|mux\.Router|def \w+\(request\b|\(req\s*[:,]|Request\b.*Response\b|"
    r"routes?_config|route_table|register_route|add_url_rule|APIRouter|url_patterns|@api_view", re.I)
WORKER_HINTS = re.compile(r"pubsub|cloud_event|CloudEvent|sqs|kinesis|@functions_framework\.cloud_event|"
                          r"celery|@task|@shared_task|def consume|onMessage|EventBridge|scheduler", re.I)
FRONTEND_HINTS = re.compile(r"from ['\"]react['\"]|import React|<[A-Z][A-Za-z]+\b[^>]*>|useState\(|useEffect\(|"
                            r"@Component|<template>|export default \{[^}]*data\(|createApp\(", re.S)
ENTRY_SCRIPT_HINTS = re.compile(r"if __name__ == ['\"]__main__['\"]|#!/(usr/)?bin/(env )?(bash|sh|zsh|python)|process\.argv|argparse")


def language_of(path: Path) -> str | None:
    if not path.suffix and path.name not in CONFIG_BASENAMES and not path.name.startswith("Dockerfile"):
        try:
            head = path.open("rb").read(64)
        except OSError:
            return None
        if head.startswith(b"#!") and any(k in head for k in (b"sh", b"bash", b"zsh")):
            return "shell"
        if head.startswith(b"#!") and b"python" in head:
            return "python"
        return None
    if path.name in CONFIG_BASENAMES or path.name.startswith("Dockerfile"):
        return "dockerfile" if "Dockerfile" in path.name or "Containerfile" in path.name else "config"
    if path.name.startswith(".env"):
        return "dotenv"
    return LANGUAGES.get(path.suffix.lower())


def role_of(rel: str, language: str, text: str) -> str:
    """One of: test, docs, generated, ci_pipeline, infra_terraform, infra_manifest,
    container, http_handler, event_worker, frontend, shared_library, script, config, other."""
    if TEST_PATHS.search(rel):
        return "test"
    if language == "config" and Path(rel).suffix in DOC_EXT:
        return "docs"
    head = text[:4000]
    if GENERATED_RE.search(head):
        return "generated"
    if CI_PATHS.search(rel):
        return "ci_pipeline"
    if language == "terraform":
        return "infra_terraform"
    if language == "dockerfile":
        return "container"
    if language == "yaml" and re.search(r"^(apiVersion|kind):", text, re.M):
        return "infra_manifest"
    if language == "yaml" and (re.search(r"^services:", text, re.M) or INFRA_PATHS.search(rel)):
        return "infra_manifest"
    if language in ("yaml", "json", "toml", "dotenv", "config"):
        return "config"
    if language in ("typescript", "javascript") and FRONTEND_HINTS.search(text) and (rel.endswith(("x",)) or "/src/" in rel and re.search(r"\.(tsx|jsx)$", rel)):
        return "frontend"
    if language in ("typescript", "javascript") and re.search(r"\.(tsx|jsx)$", rel):
        return "frontend"
    if WORKER_HINTS.search(text) and not HANDLER_HINTS.search(text):
        return "event_worker"
    if HANDLER_HINTS.search(text):
        return "http_handler"
    if language == "shell" or ENTRY_SCRIPT_HINTS.search(text) and "/scripts/" in rel:
        return "script"
    if language in ("python", "typescript", "javascript", "go", "java", "kotlin", "ruby", "php", "csharp", "rust"):
        return "shared_library"
    return "other"


def find_repos(target: Path) -> list[Path]:
    """A folder that holds repositories (children with .git) is a fleet; else one repo."""
    if (target / ".git").exists():
        return [target]
    children = sorted(p for p in target.iterdir() if p.is_dir() and (p / ".git").exists())
    return children or [target]


VENV_NAMES = {".venv", "venv", "env", ".env", "virtualenv"}


def _is_virtualenv(d: Path) -> bool:
    """`env/` is a Python virtualenv only when it has the marker files; a
    Terraform `env/` directory (per-environment root modules) must be walked."""
    return (d / "pyvenv.cfg").exists() or (d / "bin" / "activate").exists() or (d / "Scripts" / "activate.bat").exists()


def walk(repo: Path) -> list[dict]:
    files: list[dict] = []
    venv_dirs: set[Path] = set()
    for path in sorted(repo.rglob("*")):
        if not path.is_file() or path.is_symlink():
            continue
        parts = path.relative_to(repo).parts
        if any(p in SKIP_DIRS for p in parts[:-1]) or any(p.startswith(".") and p not in (".github", ".husky", ".env", ".circleci", ".gitlab-ci.yml") for p in parts[:-1]):
            continue
        skip = False
        for i, p in enumerate(parts[:-1]):
            if p in VENV_NAMES:
                d = repo.joinpath(*parts[: i + 1])
                if d in venv_dirs or _is_virtualenv(d):
                    venv_dirs.add(d)
                    skip = True
                    break
        if skip:
            continue
        rel = "/".join(parts)
        if SKIP_FILE_RE.search(rel):
            continue
        language = language_of(path)
        if language is None:
            continue
        try:
            if path.stat().st_size > MAX_FILE_BYTES:
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if "\x00" in text[:1000]:
            continue
        files.append({"path": rel, "language": language, "role": role_of(rel, language, text),
                      "bytes": len(text), "lines": text.count("\n") + 1})
    return files


def summarize(files: list[dict]) -> dict:
    return {
        "files": len(files),
        "lines": sum(f["lines"] for f in files),
        "by_language": dict(Counter(f["language"] for f in files).most_common()),
        "by_role": dict(Counter(f["role"] for f in files).most_common()),
    }


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--target", required=True)
    p.add_argument("--json", action="store_true")
    a = p.parse_args()
    target = Path(a.target).expanduser().resolve()
    for repo in find_repos(target):
        files = walk(repo)
        s = summarize(files)
        if a.json:
            print(json.dumps({"repo": str(repo), "summary": s, "files": files}, indent=1))
            continue
        print(f"\n{repo}")
        print(f"  {s['files']} files, {s['lines']:,} lines")
        print("  languages:", ", ".join(f"{k} {v}" for k, v in s["by_language"].items()))
        print("  roles:    ", ", ".join(f"{k} {v}" for k, v in s["by_role"].items()))


if __name__ == "__main__":
    main()
